---
all:
  children:
    # AVD_Lab Fabric
    Tenant:
      children:
        RE:
          children:
            Spines:
              vars:
                type: spine
              hosts:
                "RE-AVD-Spine1":
                  ansible_host: 192.168.255.11
                "RE-AVD-Spine2":
                  ansible_host: 192.168.255.12
                "RE-AVD-Spine3":
                  ansible_host: 192.168.255.13
                "RE-AVD-Spine4":
                  ansible_host: 192.168.255.14
            L3Leafs:
              vars:
                type: l3leaf
              hosts:
                "RE-AVD-Leaf1A":
                  ansible_host: 192.168.255.15
                "RE-AVD-Leaf1B":
                  ansible_host: 192.168.255.16
                "RE-AVD-Leaf2A":
                  ansible_host: 192.168.255.17
                "RE-AVD-Leaf2B":
                  ansible_host: 192.168.255.18
            L2Leafs:
              vars:
                type: l2leaf
              hosts:
                "RE-AVD-L2Leaf1A":
                  ansible_host: 192.168.255.19
                "RE-AVD-L2Leaf1B":
                  ansible_host: 192.168.255.20
                "RE-AVD-L2Leaf2A":
                  ansible_host: 192.168.255.21
                "RE-AVD-L2Leaf2B":
                  ansible_host: 192.168.255.22
