---
# Validation lab

# ******************************** Local Users ********************************

local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$6PorspAoWf2hUSNp$3CT1iPrvr7uhgCdAN2QBZuO7Aqu..EFjOK5SHUXSP44qJ91OQ/I.88B4iyDufM35wwqS1JhbmS3ejsDAxvOGL/"

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# ******************************** TerminAttr *********************************

# daemon_terminattr:
#   # Address of the gRPC server on CloudVision
#   # TCP 9910 is used for on-prem CV
#   # TCP 443 is used on CV as a Service
#   cvaddrs: # For single cluster
#     - cvp.slacker.net:9910
#   cvauth:
#     method: "token-secure"
#     token_file: "/tmp/cv-onboarding-token"
#   cvvrf: MGMT
#   # Exclude paths from Sysdb on the ingest side
#   ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
#   # Exclude paths from the shared memory table
#   smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used for on-prem CV
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - cvp.slacker.net:9910
  cvauth:
    method: "token"
    token_file: "/tmp/token"
  cvvrf: MGMT
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# ******************************* OOB Management ******************************

mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.255.1
mgmt_vrf_routing: true

# ********************************** Servers **********************************

name_servers:
  - 192.168.255.1

dns_domain: slacker.net

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
custom_structured_configuration_ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
    - name: 0.fr.pool.ntp.org
      preferred: true
      vrf: MGMT
    - name: 1.fr.pool.ntp.org
      vrf: MGMT

clock:
  timezone: US/Central

# ********************************** Radius ***********************************

# radius_server:
#   hosts:
#     - host: ubuntu.slacker.net
#       vrf: MGMT
#       key: 15331905173E2A1629373C3700
#       key_type: 7

# ip_radius_source_interfaces:
#   - name: Management1
#     vrf: MGMT

# ************************************ AAA ************************************

# [aaa_server_groups:
#   - name: FreeRadius
#     type: radius
#     servers:
#       - server: ubuntu.slacker.net

# aaa_authentication:
#   login:
#     default: group FreeRadius local
#   enable:
#     default: group FreeRadius local

# aaa_authorization:
#   exec:
#     default: group FreeRadius
#   config_commands: false
#   serial_console: false

# aaa_accounting:
#   exec:
#     default:
#       type: start-stop
#       group: FreeRadius
#   system:
#     default:
#       type: start-stop
#       group: FreeRadius
#   commands:
#     console:
#       - commands: 5,15
#         type: stop-only
#         group: FreeRadius
#         logging: true
#     default:
#       - commands: 5
#         type: stop-only
#         group: FreeRadius
#         logging: true
#       - commands: 15
#         type: stop-only
#         group: FreeRadius
#         logging: true]

# ********************************** Banners **********************************

banners:
  login: |
    _________________________________________
    | UNAUTHORIZED ACCESS TO THIS DEVICE IS   \
    | PROHIBITED!!! You must have explicit,   |
    | authorized permission to access or      |
    | configure this device. Unauthorized     |
    | attempts and actions to access or use   |
    | this system may result in civil and/or  |
    | criminal penalties. All activities      |
    | performed on this device are logged and |
    \ monitored.                              /
      ---------------------------------------
             \   ^__^
              \  (oo)\_______
                 (__)\       )\/\
                     ||----w |
                     ||     ||
    EOF
  motd: |
    ********************************************************************************
    *                                                                              *
    *              /$$$$$$            /$$             /$$                          *
    *             /$$__  $$          |__/            | $$                          *
    *            | $$  \ $$  /$$$$$$  /$$  /$$$$$$$ /$$$$$$    /$$$$$$             *
    *            | $$$$$$$$ /$$__  $$| $$ /$$_____/|_  $$_/   |____  $$            *
    *            | $$__  $$| $$  \__/| $$|  $$$$$$   | $$      /$$$$$$$            *
    *            | $$  | $$| $$      | $$ \____  $$  | $$ /$$ /$$__  $$            *
    *            | $$  | $$| $$      | $$ /$$$$$$$/  |  $$$$/|  $$$$$$$            *
    *            |__/  |__/|__/      |__/|_______/    \___/   \_______/            *
    *                                                                              *
    *                        /$$$$$$  /$$    /$$ /$$$$$$$                          *
    *                       /$$__  $$| $$   | $$| $$__  $$                         *
    *                      | $$  \ $$| $$   | $$| $$  \ $$                         *
    *                      | $$$$$$$$|  $$ / $$/| $$  | $$                         *
    *                      | $$__  $$ \  $$ $$/ | $$  | $$                         *
    *                      | $$  | $$  \  $$$/  | $$  | $$                         *
    *                      | $$  | $$   \  $/   | $$$$$$$/                         *
    *                      |__/  |__/    \_/    |_______/                          *
    *                                                                              *
    ********************************************************************************
    EOF
