# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: AVD_FABRIC

underlay_routing_protocol: BGP

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: True

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: AQQvKeimxJu+uGQ/yYvv9w==
  EVPN_OVERLAY_PEERS:
    password: AQQvKeimxJu+uGQ/yYvv9w==
  MLAG_IPv4_UNDERLAY_PEER:
    password: AQQvKeimxJu+uGQ/yYvv9w==

# Spine Switches
spine:
  defaults:
    # IP address range for /32 EVPN loopbacks on spines
    # Assign range larger then total spines
    loopback_ipv4_pool: 192.168.100.0/24
  nodes:
    avd-test-Spine1:
      id: 1
      mgmt_ip: 192.168.255.11/24
      platform: vEOS
      bgp_as: 65100
      mac_address: '0c:1d:c0:1d:62:01'
    avd-test-Spine2:
      id: 2
      mgmt_ip: 192.168.255.12/24
      platform: vEOS
      bgp_as: 65100
      mac_address: '0c:1d:c0:1d:62:02'
    avd-test-Spine3:
      id: 3
      mgmt_ip: 192.168.255.13/24
      platform: vEOS
      bgp_as: 65100
      mac_address: '0c:1d:c0:1d:62:03'
    avd-test-Spine4:
      id: 4
      mgmt_ip: 192.168.255.14/24
      platform: vEOS
      bgp_as: 65100
      mac_address: '0c:1d:c0:1d:62:04'

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # IP address range for /32 EVPN loopbacks on leafs
    # assign range larger then total leafs
    loopback_ipv4_pool: 192.168.0.0/24
    vtep_loopback_ipv4_pool: 192.168.1.0/24
    # adress pool for p2p underlay /31 links between l3leafs and spines
    # assign range larger then total [Spines * total potential leafs * 2]
    uplink_ipv4_pool: 192.168.3.0/24
    # address pool for MLAG peering
    mlag_peer_ipv4_pool: 192.168.255.0/24
    # address pool for L3 peering over MLAG peer-link
    mlag_peer_l3_ipv4_pool: 192.168.254.0/24
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_priority: 16384
    spanning_tree_mode: mstp
  node_groups:
    pod0:
      bgp_as: 65001
      nodes:
        avd-test-Leaf1A:
          id: 1
          mgmt_ip: 192.168.255.15/24
          platform: vEOS
          uplink_switches: ['avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4', 'avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4']
          uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4', 'Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
          uplink_switch_interfaces: ['Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1', 'Ethernet1']
          mac_address: '0c:1d:c0:1d:62:05'
          mlag_interfaces: ['Ethernet5']
        avd-test-Leaf1B:
          id: 2
          mgmt_ip: 192.168.255.16/24
          platform: vEOS
          uplink_switches: ['avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4', 'avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4']
          uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4', 'Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
          uplink_switch_interfaces: ['Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2', 'Ethernet2']
          mac_address: '0c:1d:c0:1d:62:06'
          mlag_interfaces: ['Ethernet5']
    pod1:
      bgp_as: 65002
      nodes:
        avd-test-Leaf2A:
          id: 3
          mgmt_ip: 192.168.255.17/24
          platform: vEOS
          uplink_switches: ['avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4', 'avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4']
          uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4', 'Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
          uplink_switch_interfaces: ['Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3', 'Ethernet3']
          mac_address: '0c:1d:c0:1d:62:07'
          mlag_interfaces: ['Ethernet5']
        avd-test-Leaf2B:
          id: 4
          mgmt_ip: 192.168.255.18/24
          platform: vEOS
          uplink_switches: ['avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4', 'avd-test-Spine1', 'avd-test-Spine2', 'avd-test-Spine3', 'avd-test-Spine4']
          uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4', 'Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
          uplink_switch_interfaces: ['Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4', 'Ethernet4']
          mac_address: '0c:1d:c0:1d:62:08'
          mlag_interfaces: ['Ethernet5']

p2p_uplinks_mtu: 9214
