---
# OOB Management network default gateway.
mgmt_gateway: 192.168.255.1

# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$2YPH6yCQ.xAFxuUh$t0uUeTzX1VLj2xu4il.//BIzI46CNswZNdD..vs2N.jRim65PPA8BqrSoft.2h5duvcQ27XULKnwmEp6aRZHT."
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$wh5/7CrF9CTrG0nk$RWaK9mq0OvSe1yRnDE6bkYNa6SRHte8Pt3pGa0fxTN0uKuF2TddOGOrkzdwsRul5DTYi1Sr7UYYXkbEuQClXl0"

# Cloud Vision server
cvp_instance_ips:
  - 192.168.2.137
cvp_ingestauth_key: 

# dns servers
name_servers:
 - 192.168.2.1
 - 192.168.255.1

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment
ntp_servers:
 - 192.168.2.1
 - 192.168.255.1

# dns domain
dns_domain: slacker.eve
