---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: "RE"
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: reset local folders for output
      tags:
        - "generate"
        - "reset"
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags:
        - "build"
        - "generate"
        - "deploy"
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags:
        - "build"
        - "generate"
        - "deploy"
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVaaS
  hosts: "cvaas"
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CvaaS provisioning
      tags:
        - "deploy"
        - "provision"
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: "RE"
        configlets_prefix: "re"
        device_filter: "RE-AVD-"
        state: present
        cv_collection: v3


