---
- name: validate states on EOS devices
  hosts: RE
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  vars:
    ansible_user: admin
    ansible_password: arista123
    ansible_network_os: arista.eos.eos
    # Configure privilege escalation
    ansible_become: true
    ansible_become_method: enable
    # HTTPAPI configuration
    ansible_connection: httpapi
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false

  tasks:

    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
