---
###########################################################
# -------------------- Port Profiles -------------------- #
###########################################################

port_profiles:
  - profile: TENANT_A_VL110_MLAG
    mode: access
    vlans: "110"
    port_channel:
      mode: "on"

  - profile: TENANT_A_VL1191_MLAG
    mode: access
    vlans: "1191"
    port_channel:
      mode: "on"

  - profile: TENANT_A_VL1191_SINGLE
    mode: access
    vlans: "1191"

  - profile: TENANT_A_VL130_MLAG
    mode: access
    vlans: "130"
    port_channel:
      mode: "on"

###########################################################
# ---------------- Endpoint Connectivity ---------------- #
###########################################################

servers:
  # ----------------------------------------------------- #
  # Site1 RACKA Endpoints
  # ----------------------------------------------------- #
  - name: Host1
    rack: RackA
    adapters:
      - switch_ports:
          - Ethernet5
          - Ethernet5
        switches:
          - RE-AVD-L2Leaf1A
          - RE-AVD-L2Leaf1B
        endpoint_ports:
          - Ethernet1
          - Ethernet2
        profile: TENANT_A_VL110_MLAG

  - name: vl1191_host
    rack: RackA
    adapters:
      - switch_ports:
          - Ethernet6
        switches:
          - RE-AVD-L2Leaf1A
        endpoint_ports:
          - ens3
        profile: TENANT_A_VL1191_SINGLE

  # ----------------------------------------------------- #
  # Site1 RACKB Endpoints
  # ----------------------------------------------------- #
  - name: avd-svr01
    rack: RackB
    adapters:
      - switch_ports:
          - Ethernet5
          - Ethernet5
        switches:
          - RE-AVD-L2Leaf2A
          - RE-AVD-L2Leaf2B
        endpoint_ports:
          - ens3
          - ens4
        profile: TENANT_A_VL130_MLAG

  - name: Host2
    rack: RackB
    adapters:
      - switch_ports:
          - Ethernet6
          - Ethernet6
        switches:
          - RE-AVD-L2Leaf2A
          - RE-AVD-L2Leaf2B
        endpoint_ports:
          - Ethernet1
          - Ethernet2
        profile: TENANT_A_VL110_MLAG
