---
###########################################################
# ------------------ Fabric Variables ------------------- #
###########################################################

# ------------------------------------------------------- #
# L3LS Fabric Values - update these values with caution
# SOME CHANGES COULD BE DISRUPTIVE.
# ------------------------------------------------------- #

fabric_name: "RE"

# ------------------------------------------------------- #
# Enable vlan aware bundles
# ------------------------------------------------------- #

evpn_vlan_aware_bundles: true

# ------------------------------------------------------- #
# Shutdown unused interfaces
# ------------------------------------------------------- #

interface_defaults:
  ethernet:
    shutdown: true

# ------------------------------------------------------- #
# BGP peer groups passwords
# ------------------------------------------------------- #

bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  mlag_ipv4_underlay_peer:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# ------------------------------------------------------- #
# Disable BGP update wait-install
# This command doesn't work in vEOS
# ------------------------------------------------------- #

bgp_update_wait_install: false

# ------------------------------------------------------- #
# Override for vEOS Lab Caveats
# ------------------------------------------------------- #

p2p_uplinks_mtu: 1500

# ------------------------------------------------------- #
# Adjust default BFD values
# ------------------------------------------------------- #

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

###########################################################
# ------------------- Node Type Keys -------------------- #
###########################################################

# ------------------------------------------------------- #
# Spine Switches
# ------------------------------------------------------- #

spine:
  defaults:
    platform: "vEOS-LAB"
    bgp_as: "65001"
    loopback_ipv4_pool: "192.168.254.0/24"
    bgp_defaults:
      - "distance bgp 20 200 200"
      - "graceful-restart restart-time 300"
      - "graceful-restart"
  nodes:
    - name: "RE-AVD-Spine1"
      id: 11
      mgmt_ip: "192.168.255.11/24"
    - name: "RE-AVD-Spine2"
      id: 12
      mgmt_ip: "192.168.255.12/24"
    - name: "RE-AVD-Spine3"
      id: 13
      mgmt_ip: "192.168.255.13/24"
    - name: "RE-AVD-Spine4"
      id: 14
      mgmt_ip: "192.168.255.14/24"

# ------------------------------------------------------- #
# L3Leaf Switches
# ------------------------------------------------------- #

l3leaf:
  defaults:
    platform: "vEOS-LAB"
    loopback_ipv4_pool: "192.168.254.0/24"
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: "192.168.253.0/24"
    always_configure_ip_routing: true
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"
      - "Ethernet3"
      - "Ethernet4"
    uplink_switches:
      - "RE-AVD-Spine1"
      - "RE-AVD-Spine2"
      - "RE-AVD-Spine3"
      - "RE-AVD-Spine4"
    uplink_ipv4_pool: "192.168.0.0/23"
    mlag_interfaces:
      - "Ethernet5"
      - "Ethernet6"
    mlag_peer_ipv4_pool: "192.168.252.0/24"
    mlag_peer_l3_ipv4_pool: "192.168.251.0/24"
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_defaults:
      - "distance bgp 20 200 200"
      - "graceful-restart restart-time 300"
      - "graceful-restart"
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: "RE-AVD-Leaf1"
      bgp_as: "65101"
      nodes:
        - name: "RE-AVD-Leaf1A"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
          id: 15
          mgmt_ip: "192.168.255.15/24"
          uplink_switch_interfaces:
            - "Ethernet1"
            - "Ethernet1"
            - "Ethernet1"
            - "Ethernet1"
        - name: "RE-AVD-Leaf1B"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "web"
              - "appzone"
          id: 16
          mgmt_ip: "192.168.255.16/24"
          uplink_switch_interfaces:
            - "Ethernet2"
            - "Ethernet2"
            - "Ethernet2"
            - "Ethernet2"
    - group: "RE-AVD-Leaf2"
      bgp_as: "65102"
      filter:
        tenants:
          - "Tenant_A"
        tags:
          - "opzone"
          - "web"
          - "appzone"
      nodes:
        - name: "RE-AVD-Leaf2A"
          id: 17
          mgmt_ip: "192.168.255.17/24"
          uplink_switch_interfaces:
            - "Ethernet3"
            - "Ethernet3"
            - "Ethernet3"
            - "Ethernet3"
        - name: "RE-AVD-Leaf2B"
          id: 18
          mgmt_ip: "192.168.255.18/24"
          uplink_switch_interfaces:
            - "Ethernet4"
            - "Ethernet4"
            - "Ethernet4"
            - "Ethernet4"
    - group: "RE-AVD-BrdrLeaf1"
      bgp_as: "65103"
      nodes:
        - name: "RE-AVD-BrdrLeaf1A"
          id: 19
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
              - "internet"
          mgmt_ip: "192.168.255.19/24"
          uplink_switch_interfaces:
            - "Ethernet5"
            - "Ethernet5"
            - "Ethernet5"
            - "Ethernet5"
        - name: "RE-AVD-BrdrLeaf1B"
          id: 20
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
              - "internet"
          mgmt_ip: "192.168.255.20/24"
          uplink_switch_interfaces:
            - "Ethernet6"
            - "Ethernet6"
            - "Ethernet6"
            - "Ethernet6"

# ------------------------------------------------------- #
# L2Leaf Switches
# ------------------------------------------------------- #

l2leaf:
  defaults:
    platform: "vEOS-LAB"
    uplink_interfaces:
      - "Ethernet1"
      - "Ethernet2"
    mlag_interfaces:
      - "Ethernet3"
      - "Ethernet4"
    mlag_peer_ipv4_pool: "192.168.252.0/24"
    mlag_peer_l3_ipv4_pool: "192.168.251.0/24/24"
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    mlag: true
  node_groups:
    - group: "RE-AVD-L2Leaf1"
      uplink_switches:
        - "RE-AVD-Leaf1A"
        - "RE-AVD-Leaf1B"
      nodes:
        - name: "RE-AVD-L2Leaf1A"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
          id: 21
          mgmt_ip: "192.168.255.21/24"
          uplink_switch_interfaces:
            - "Ethernet7"
            - "Ethernet7"
        - name: "RE-AVD-L2Leaf1B"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
          id: 22
          mgmt_ip: "192.168.255.22/24"
          uplink_switch_interfaces:
            - "Ethernet8"
            - "Ethernet8"
    - group: "RE-AVD-L2Leaf2"
      uplink_switches:
        - "RE-AVD-Leaf2A"
        - "RE-AVD-Leaf2B"
      nodes:
        - name: "RE-AVD-L2Leaf2A"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
          id: 23
          mgmt_ip: "192.168.255.23/24"
          uplink_switch_interfaces:
            - "Ethernet7"
            - "Ethernet7"
        - name: "RE-AVD-L2Leaf2B"
          filter:
            tenants:
              - "Tenant_A"
            tags:
              - "opzone"
              - "appzone"
          id: 24
          mgmt_ip: "192.168.255.24/24"
          uplink_switch_interfaces:
            - "Ethernet8"
            - "Ethernet8"

