---
# Port Profiles
port_profiles:
  - profile: TENANT_A_B
    mode: trunk
    vlans: "110-111,210-211"

  - profile: TENANT_A
    mode: access
    vlans: "110"

  - profile: TENANT_B
    mode: trunk
    vlans: "210-211"

# Servers
servers:
  - name: server01
    rack: RackA
    adapters:
      - switch_ports:
          - Ethernet5
          - Ethernet5
        switches:
          - RE-AVD-L2Leaf1A
          - RE-AVD-L2Leaf1B
        endpoint_ports:
          - ens3
          - ens4
        profile: TENANT_A

  - name: server02
    rack: RackA
    adapters:
      - switch_ports:
          - Ethernet5
          - Ethernet5
        switches:
          - RE-AVD-L2Leaf2A
          - RE-AVD-L2Leaf2B
        endpoint_ports:
          - ens3
          - ens4
        profile: TENANT_A

  - name: server03
    rack: RackA
    adapters:
      - switch_ports:
          - Ethernet6
          - Ethernet6
        switches:
          - RE-AVD-L2Leaf2A
          - RE-AVD-L2Leaf2B
        endpoint_ports:
          - ens3
          - ens4
        profile: TENANT_A
