---
###########################################################
# ---------------- DC1 Tenants Networks ----------------- #
# ---- Documentation of Tenant specific information: ---- #
# -------------------- VRFs/VLANs ----------------------- #
###########################################################

tenants:
  #########################################################
  # --------------------- Tenant A ---------------------- #
  #########################################################
  - name: "Tenant_A"
  # ----------------------------------------------------- #
  # Layer 2 VLANs
  # ----------------------------------------------------- #
    l2vlans:
      - id: 160
        vni_override: 55160
        name: Tenant_A_VMOTION
        tags:
          - "vmotion"
      - id: 161
        name: Tenant_A_NFS
        tags:
          - "nfs"
  # ----------------------------------------------------- #
  # VRFs & SVIs
  # ----------------------------------------------------- #
    mac_vrf_vni_base: 10000
    vrfs:
      - name: "Internet"
        vrf_vni: 999
        l3_interfaces:
          - interfaces:
            - "Ethernet7"
            - "Ethernet7"
            ip_addresses:
              - "192.168.20.23/23"
              - "192.168.20.24/23"
            description: "Internet Connection"
            nodes:
              - "RE-AVD-BrdrLeaf1A"
              - "RE-AVD-BrdrLeaf1B"
        static_routes:
          - destination_address_prefix: "0.0.0.0/0"
            gateway: "192.168.20.1"
            nodes:
              - "RE-AVD-BrdrLeaf1A"
              - "RE-AVD-BrdrLeaf1B"
      - name: "Tenant_A_OP_Zone"
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: "10.255.1.0/24"
        svis:
          - id: 110
            name: "Tenant_A_OP_Zone_1"
            tags:
              - "tenant_a_opzone"
            enabled: true
            ip_address_virtual: "10.1.10.1/24"
          - id: 111
            vni_override: 50111
            name: "Tenant_A_OP_Zone_2"
            tags:
              - "tenant_a_opzone"
            enabled: true
            ip_address_virtual: "10.1.11.1/24"
          - id: 112
            vni_override: 50112
            name: "Tenant_A_OP_Zone_3"
            tags:
              - "tenant_a_opzone"
            enabled: true
            ip_address_virtual: "10.1.12.254/24"
          - id: 1191
            vni_override: 51192
            name: "Test_VLAN"
            tags:
              - "tenant_a_opzone"
            enabled: true
            ip_address_virtual: "10.11.91.1/24"
      - name: "Tenant_A_WEB_Zone"
        vrf_vni: 11
        svis:
          - id: 120
            name: "Tenant_A_WEB_Zone_1"
            tags:
              - "tenant_a_web"
              - "tenant_a_erp1"
            enabled: true
            ip_address_virtual: "10.1.20.1/24"
          - id: 121
            name: "Tenant_A_WEBZone_2"
            tags:
              - "tenant_a_web"
            enabled: true
            ip_address_virtual: "10.1.21.1/24"
      - name: "Tenant_A_APP_Zone"
        vrf_vni: 12
        svis:
          - id: 130
            name: "Tenant_A_APP_Zone_1"
            tags:
              - "tenant_a_app"
              - "tenant_a_erp1"
            enabled: true
            ip_address_virtual: "10.1.30.1/24"
          - id: 131
            name: "Tenant_A_APP_Zone_2"
            tags:
              - "tenant_a_app"
            enabled: true
            ip_address_virtual: "10.1.31.254/24"
      - name: "Tenant_A_DB_Zone"
        vrf_vni: 13
        svis:
          - id: 140
            name: "Tenant_A_DB_BZone_1"
            tags:
              - "tenant_a_db"
              - "tenant_a_erp1"
            enabled: true
            ip_address_virtual: "10.1.40.1/24"
          - id: 141
            name: "Tenant_A_DB_Zone_2"
            tags:
              - "tenant_a_db"
            enabled: true
            ip_address_virtual: "10.1.41.1/24"
      - name: "Tenant_A_WAN_Zone"
        vrf_vni: 14
        svis:
          - id: 150
            name: "Tenant_A_WAN_Zone_1"
            tags:
              - "tenant_b_wan"
            enabled: true
            ip_address_virtual: "10.1.40.1/24"

  # #########################################################
  # # --------------------- Tenant B ---------------------- #
  # #########################################################
  # - name: "Tenant_B"
  # # ----------------------------------------------------- #
  # # VRFs & SVIs
  # # ----------------------------------------------------- #
  #   mac_vrf_vni_base: 20000
  #   vrfs:
  #     - name: "Tenant_B_OP_Zone"
  #       vrf_vni: 20
  #       svis:
  #         - id: 210
  #           name: "Tenant_B_OP_Zone_1"
  #           tags:
  #             - "tenant_b_opzone"
  #           enabled: true
  #           ip_address_virtual: "10.2.10.1/24"
  #         - id: 211
  #           name: "Tenant_B_OP_Zone_2"
  #           tags:
  #             - "tenant_b_opzone"
  #           enabled: true
  #           ip_address_virtual: "10.2.11.1/24"
  #     - name: "Tenant_B_WAN_Zone"
  #       vrf_vni: 21
  #       svis:
  #         - id: 250
  #           name: "Tenant_B_WAN_Zone_1"
  #           tags:
  #             - "tenant_b_wan"
  #           enabled: true
  #           ip_address_virtual: "10.2.50.1/24"

  # #########################################################
  # # --------------------- Tenant C ---------------------- #
  # #########################################################
  # - name: "Tenant_C"
  # # ----------------------------------------------------- #
  # # VRFs & SVIs
  # # ----------------------------------------------------- #
  #   mac_vrf_vni_base: 30000
  #   vrfs:
  #     - name: "Tenant_C_OP_Zone"
  #       vrf_vni: 30
  #       svis:
  #         - id: 310
  #           name: "Tenant_C_OP_Zone_1"
  #           tags:
  #             - "tenant_c_opzone"
  #           enabled: true
  #           ip_address_virtual: "10.3.10.1/24"
  #         - id: 311
  #           name: "Tenant_C_OP_Zone_2"
  #           tags:
  #             - "tenant_c_opzone"
  #           enabled: true
  #           ip_address_virtual: "10.3.11.1/24"
  #     - name: "Tenant_C_WAN_Zone"
  #       vrf_vni: 31
  #       svis:
  #         - id: 350
  #           name: "Tenant_C_WAN_Zone_1"
  #           tags:
  #             - "tenant_c_wan"
  #           enabled: true
  #           ip_address_virtual: "10.3.50.1/24"
