---
###########################################################
# ---------------- DC1 Tenants Networks ----------------- #
# ---- Documentation of Tenant specific information: ---- #
# -------------------- VRFs/VLANs ----------------------- #
###########################################################

tenants:

  #########################################################
  # --------------------- Tenant A ---------------------- #
  #########################################################

  - name: "Tenant_A"

  # ----------------------------------------------------- #
  # Layer 2 VLANs
  # ----------------------------------------------------- #

    mac_vrf_vni_base: 20000
    l2vlans:
      - id: 200
        name: "Vlan200"
      - id: 201
        name: "Vlan201"

  # ----------------------------------------------------- #
  # VRFs & SVIs
  # ----------------------------------------------------- #

    vrfs:
      - name: "Internet"
        vrf_vni: 999
        l3_interfaces:
          - interfaces:
            - "Ethernet7"
            - "Ethernet7"
            ip_addresses:
              - "192.168.20.23/23"
              - "192.168.20.24/23"
            description: "Internet Connection"
            nodes:
              - "RE-AVD-BrdrLeaf1A"
              - "RE-AVD-BrdrLeaf1B"
        static_routes:
          - destination_address_prefix: "0.0.0.0/0"
            gateway: "192.168.20.1"
            nodes:
              - "RE-AVD-BrdrLeaf1A"
              - "RE-AVD-BrdrLeaf1B"
      - name: "App_Zone"
        vrf_vni: 100
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: "192.168.100.0/24"
        svis:
          - id: 110
            name: "App_Zone_110"
            tags:
              - "appzone"
            enabled: true
            ip_address_virtual: "192.168.110.1/24"
          - id: 111
            name: "App_Zone_111"
            tags:
              - "appzone"
            enabled: true
            ip_address_virtual: "192.168.111.1/24"
          - id: 112
            name: "App_Zone_112"
            tags:
              - "appzone"
            enabled: true
            ip_address_virtual: "192.168.112.1/24"
      - name: "Op_Zone"
        vrf_vni: 200
        vtep_diagnostic:
          loopback: 101
          loopback_ip_range: "192.168.101.0/24"
        svis:
          - id: 120
            name: "Op_Zone_120"
            tags:
              - "opzone"
            enabled: true
            ip_address_virtual: "192.168.120.1/24"
          - id: 121
            name: "Op_Zone_121"
            tags:
              - "opzone"
            enabled: true
            ip_address_virtual: "192.168.121.1/24"
